"""create webhook_requests table

Revision ID: 61d271d41dfd
Revises: 
Create Date: 2026-04-11 20:27:10.683034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d271d41dfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_requests_client_ip'), 'webhook_requests', ['client_ip'], unique=False)
    op.create_index(op.f('ix_webhook_requests_id'), 'webhook_requests', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_requests_webhook_id'), 'webhook_requests', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_requests_webhook_id'), table_name='webhook_requests')
    op.drop_index(op.f('ix_webhook_requests_id'), table_name='webhook_requests')
    op.drop_index(op.f('ix_webhook_requests_client_ip'), table_name='webhook_requests')
    op.drop_table('webhook_requests')
    # ### end Alembic commands ###
